/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ie.gti.asdl.rey.gtirecord.desktop.ui.frame;

import java.awt.*;
import java.awt.event.*;
import java.util.Optional;
import javax.swing.*;

import ie.gti.asdl.rey.gtirecord.model.entity.User;
import ie.gti.asdl.rey.gtirecord.core.ServiceManager;
import ie.gti.asdl.rey.gtirecord.core.service.UserService;
import ie.gti.asdl.rey.gtirecord.desktop.ui.AbstractFrame;
import ie.gti.asdl.rey.gtirecord.desktop.ui.FrameManager;

import static ie.gti.asdl.rey.gtirecord.desktop.ui.FrameManager.FrameType.MAIN;

/**
 *
 * @author Andrei
 */
public class LoginFrame extends AbstractFrame {

    private boolean isActivated;

    private final UserService userService;

    public LoginFrame(FrameManager frameManager, ServiceManager serviceManager) {
        super(frameManager);
        userService = serviceManager.getUserService();
        initComponents();
        initFrame();
        init();
    }
    
    
    private void init() {
        resizeLabelIcon();
    }

    private void resizeLabelIcon() {
        Icon gretbIcon = lblGretb.getIcon(); // myLabel — это твой JLabel
        if (gretbIcon instanceof ImageIcon imageIcon) {
            Image image = imageIcon.getImage();
            Image scaledImage = image.getScaledInstance(216, 84, Image.SCALE_SMOOTH);
            lblGretb.setIcon(new ImageIcon(scaledImage));
        }

        Icon gtiIcon = lblGti.getIcon(); // myLabel — это твой JLabel
        if (gtiIcon instanceof ImageIcon imageIcon) {
            Image image = imageIcon.getImage();
            Image scaledImage = image.getScaledInstance(152, 120, Image.SCALE_SMOOTH);
            lblGti.setIcon(new ImageIcon(scaledImage));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsernameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLoginBtn = new javax.swing.JButton();
        jPasswordTF = new javax.swing.JPasswordField();
        jExitBtn = new javax.swing.JButton();
        lblGti = new javax.swing.JLabel();
        lblGretb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jUsernameTF.setText("johnm");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Password");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("GTI RECORD SYSTEM");

        jLoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLoginBtn.setForeground(new java.awt.Color(0, 51, 204));
        jLoginBtn.setText("Login");
        jLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginBtnActionPerformed(evt);
            }
        });
        jLoginBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLoginBtnKeyPressed(evt);
            }
        });

        jPasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordTFActionPerformed(evt);
            }
        });
        jPasswordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordTFKeyPressed(evt);
            }
        });

        jExitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jExitBtn.setForeground(new java.awt.Color(0, 51, 204));
        jExitBtn.setText("Exit");
        jExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitBtnActionPerformed(evt);
            }
        });

        lblGti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gti-logo.png"))); // NOI18N

        lblGretb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gretb-logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblGti)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jUsernameTF)
                    .addComponent(jPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblGretb, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblGti))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(jLoginBtn))
                            .addComponent(lblGretb, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jExitBtn)))
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginBtnActionPerformed
        Optional<User> userOpt = userService.getByUsername(jUsernameTF.getText());

        if (userOpt.isEmpty() || (! userOpt.get().getPassword().equals(String.valueOf(jPasswordTF.getPassword())))) {
            JOptionPane.showMessageDialog(this, "Invalid username or password");
        } else {
            getFrameManager().setActiveUser(userOpt.get());
            getFrameManager().showSub(MAIN);
        }

    }//GEN-LAST:event_jLoginBtnActionPerformed

    private void jPasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordTFActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (! isActivated) {
            this.setLocationRelativeTo(null);
            isActivated = true;
        }
    }//GEN-LAST:event_formWindowActivated

    private void jPasswordTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordTFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jLoginBtnActionPerformed(null);
        }
    }//GEN-LAST:event_jPasswordTFKeyPressed

    private void jLoginBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLoginBtnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jLoginBtnActionPerformed(null);
        }
    }//GEN-LAST:event_jLoginBtnKeyPressed

    private void jExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLoginBtn;
    private javax.swing.JPasswordField jPasswordTF;
    private javax.swing.JTextField jUsernameTF;
    private javax.swing.JLabel lblGretb;
    private javax.swing.JLabel lblGti;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    @Override
    protected int getDefaultCloseOperationValue() {
        return JFrame.EXIT_ON_CLOSE;
    }
}
