/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ie.gti.asdl.rey.gtirecord.desktop.ui.frame;

import ie.gti.asdl.rey.gtirecord.model.entity.Role;
import ie.gti.asdl.rey.gtirecord.model.entity.User;
import ie.gti.asdl.rey.gtirecord.core.ServiceManager;
import ie.gti.asdl.rey.gtirecord.desktop.ui.AbstractFrame;
import ie.gti.asdl.rey.gtirecord.desktop.ui.FrameManager;
import ie.gti.asdl.rey.gtirecord.model.util.UserUtils;

import java.util.Map;
import java.util.stream.Collectors;

import static ie.gti.asdl.rey.gtirecord.desktop.ui.FrameManager.FrameType.*;

/**
 *
 * @author Andrei
 */
public class MainFrame extends AbstractFrame {

    private static final String STUDENT_TAB_TITLE = "Student";

    private static final String TEACHER_TAB_TITLE = "Teacher";

    private static final String ADMIN_TAB_TITLE = "Administrator";

    private static final Map<Role, String> roleToTabTitleMap = Map.of(
            Role.RoleType.ADMIN.asRole(), ADMIN_TAB_TITLE,
            Role.RoleType.TEACHER.asRole(), TEACHER_TAB_TITLE,
            Role.RoleType.STUDENT.asRole(), STUDENT_TAB_TITLE);

    /**
     * Creates new form MainFrame
     */
    public MainFrame(FrameManager frameManager, ServiceManager serviceManager) {
        super(frameManager);
        initComponents();
        initFrame();
    }

    @Override
    protected void onFrameShown() {
        super.onFrameShown();
        updateUI();
    }

    public void updateUI() {
        jTabbedPane.remove(jAdminTabPanel);
        jTabbedPane.remove(jTeacherTabPanel);
        jTabbedPane.remove(jStudentTabPanel);

        User user = getFrameManager().getActiveUser();

        String title = user.getRoles().stream().map(roleToTabTitleMap::get).collect(Collectors.joining(" | "));
        jTabbedPane.add(title, jAdminTabPanel);

        lblLoggedInUsername.setText(user.getUsername());
        
//        if (UserUtils.isAdmin(user)) {
//        jTabbedPane.add(title, jAdminTabPanel);
//        }

//        if (UserUtils.isTeacher(user)) {
//            jTabbedPane.add(TEACHER_TAB_TITLE, jTeacherTabPanel);
//        }
//
//        if (UserUtils.isStudent(user)) {
//            jTabbedPane.add(STUDENT_TAB_TITLE, jStudentTabPanel);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jStudentTabPanel = new javax.swing.JPanel();
        btnModuleStudent = new javax.swing.JButton();
        btnUserStudent = new javax.swing.JButton();
        btnTeacherStudent = new javax.swing.JButton();
        btnDepartmentStudent = new javax.swing.JButton();
        btnCourseStudent = new javax.swing.JButton();
        btnStudentStudent = new javax.swing.JButton();
        btnAssignmentsStudent = new javax.swing.JButton();
        btnGroupStudent = new javax.swing.JButton();
        jTeacherTabPanel = new javax.swing.JPanel();
        btnModuleTeacher = new javax.swing.JButton();
        btnUserTeacher = new javax.swing.JButton();
        btnTeacherTeacher = new javax.swing.JButton();
        btnDepartmentTeacher = new javax.swing.JButton();
        btnCourseTeacher = new javax.swing.JButton();
        btnStudentTeacher = new javax.swing.JButton();
        btnAssignmentsTeacher = new javax.swing.JButton();
        btnGroupTeacher = new javax.swing.JButton();
        jAdminTabPanel = new javax.swing.JPanel();
        btnModuleAdmin = new javax.swing.JButton();
        btnUserAdmin = new javax.swing.JButton();
        btnTeacherAdmin = new javax.swing.JButton();
        btnDepartmentAdmin = new javax.swing.JButton();
        btnCourseAdmin = new javax.swing.JButton();
        btnStudentAdmin = new javax.swing.JButton();
        btnAssignmentAdmin = new javax.swing.JButton();
        btnGroupAdmin = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        pnlLoggedInAs4 = new javax.swing.JPanel();
        lblLoggedInUsername = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setResizable(false);

        btnModuleStudent.setText("MODULES");
        btnModuleStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuleStudentActionPerformed(evt);
            }
        });

        btnUserStudent.setText("USERS");
        btnUserStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserStudentActionPerformed(evt);
            }
        });

        btnTeacherStudent.setText("TEACHERS");
        btnTeacherStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherStudentActionPerformed(evt);
            }
        });

        btnDepartmentStudent.setText("DEPARTMENTS");
        btnDepartmentStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentStudentActionPerformed(evt);
            }
        });

        btnCourseStudent.setText("COURSES");
        btnCourseStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseStudentActionPerformed(evt);
            }
        });

        btnStudentStudent.setText("STUDENTS");
        btnStudentStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentStudentActionPerformed(evt);
            }
        });

        btnAssignmentsStudent.setText("ASSIGNMENTS");
        btnAssignmentsStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentsStudentActionPerformed(evt);
            }
        });

        btnGroupStudent.setText("GROUPS");
        btnGroupStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jStudentTabPanelLayout = new javax.swing.GroupLayout(jStudentTabPanel);
        jStudentTabPanel.setLayout(jStudentTabPanelLayout);
        jStudentTabPanelLayout.setHorizontalGroup(
            jStudentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStudentTabPanelLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jStudentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStudentStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeacherStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(jStudentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssignmentsStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGroupStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jStudentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCourseStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepartmentStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuleStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );
        jStudentTabPanelLayout.setVerticalGroup(
            jStudentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStudentTabPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jStudentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepartmentStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jStudentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeacherStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGroupStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jStudentTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuleStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignmentsStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Student", jStudentTabPanel);

        btnModuleTeacher.setText("MODULES");
        btnModuleTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuleTeacherActionPerformed(evt);
            }
        });

        btnUserTeacher.setText("USERS");
        btnUserTeacher.setEnabled(false);
        btnUserTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserTeacherActionPerformed(evt);
            }
        });

        btnTeacherTeacher.setText("TEACHERS");
        btnTeacherTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherTeacherActionPerformed(evt);
            }
        });

        btnDepartmentTeacher.setText("DEPARTMENTS");
        btnDepartmentTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentTeacherActionPerformed(evt);
            }
        });

        btnCourseTeacher.setText("COURSES");
        btnCourseTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseTeacherActionPerformed(evt);
            }
        });

        btnStudentTeacher.setText("STUDENTS");
        btnStudentTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentTeacherActionPerformed(evt);
            }
        });

        btnAssignmentsTeacher.setText("ASSIGNMENTS");
        btnAssignmentsTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentsTeacherActionPerformed(evt);
            }
        });

        btnGroupTeacher.setText("GROUPS");
        btnGroupTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTeacherTabPanelLayout = new javax.swing.GroupLayout(jTeacherTabPanel);
        jTeacherTabPanel.setLayout(jTeacherTabPanelLayout);
        jTeacherTabPanelLayout.setHorizontalGroup(
            jTeacherTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTeacherTabPanelLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jTeacherTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStudentTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeacherTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(jTeacherTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssignmentsTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGroupTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jTeacherTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCourseTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepartmentTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuleTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );
        jTeacherTabPanelLayout.setVerticalGroup(
            jTeacherTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTeacherTabPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jTeacherTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepartmentTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jTeacherTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeacherTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGroupTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jTeacherTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuleTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignmentsTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Teacher", jTeacherTabPanel);

        btnModuleAdmin.setText("MODULES");
        btnModuleAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuleAdminActionPerformed(evt);
            }
        });

        btnUserAdmin.setText("USERS");
        btnUserAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAdminActionPerformed(evt);
            }
        });

        btnTeacherAdmin.setText("TEACHERS");
        btnTeacherAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherAdminActionPerformed(evt);
            }
        });

        btnDepartmentAdmin.setText("DEPARTMENTS");
        btnDepartmentAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentAdminActionPerformed(evt);
            }
        });

        btnCourseAdmin.setText("COURSES");
        btnCourseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseAdminActionPerformed(evt);
            }
        });

        btnStudentAdmin.setText("STUDENTS");
        btnStudentAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentAdminActionPerformed(evt);
            }
        });

        btnAssignmentAdmin.setText("ASSIGNMENTS");
        btnAssignmentAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentAdminActionPerformed(evt);
            }
        });

        btnGroupAdmin.setText("GROUPS");
        btnGroupAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAdminTabPanelLayout = new javax.swing.GroupLayout(jAdminTabPanel);
        jAdminTabPanel.setLayout(jAdminTabPanelLayout);
        jAdminTabPanelLayout.setHorizontalGroup(
            jAdminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdminTabPanelLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jAdminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStudentAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeacherAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(jAdminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssignmentAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGroupAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jAdminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCourseAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepartmentAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );
        jAdminTabPanelLayout.setVerticalGroup(
            jAdminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAdminTabPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jAdminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepartmentAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jAdminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeacherAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGroupAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jAdminTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignmentAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Administrator", jAdminTabPanel);

        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblLoggedInUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLoggedInUsername.setForeground(new java.awt.Color(255, 0, 0));
        lblLoggedInUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoggedInUsername.setText("logged in as ");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile.png"))); // NOI18N

        javax.swing.GroupLayout pnlLoggedInAs4Layout = new javax.swing.GroupLayout(pnlLoggedInAs4);
        pnlLoggedInAs4.setLayout(pnlLoggedInAs4Layout);
        pnlLoggedInAs4Layout.setHorizontalGroup(
            pnlLoggedInAs4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoggedInAs4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoggedInUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLoggedInAs4Layout.setVerticalGroup(
            pnlLoggedInAs4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .addGroup(pnlLoggedInAs4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblLoggedInUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlLoggedInAs4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlLoggedInAs4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        getFrameManager().logout();
        getFrameManager().showParent();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnDepartmentAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentAdminActionPerformed
        getFrameManager().showSub(DEPARTMENT);
    }//GEN-LAST:event_btnDepartmentAdminActionPerformed

    private void btnTeacherAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherAdminActionPerformed
        getFrameManager().showSub(TEACHER);
    }//GEN-LAST:event_btnTeacherAdminActionPerformed

    private void btnUserAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAdminActionPerformed
        getFrameManager().showSub(USER);
    }//GEN-LAST:event_btnUserAdminActionPerformed

    private void btnCourseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseAdminActionPerformed
        getFrameManager().showSub(COURSE);
    }//GEN-LAST:event_btnCourseAdminActionPerformed

    private void btnStudentAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentAdminActionPerformed
        getFrameManager().showSub(STUDENT);
    }//GEN-LAST:event_btnStudentAdminActionPerformed

    private void btnModuleAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuleAdminActionPerformed
        getFrameManager().showSub(MODULE);
    }//GEN-LAST:event_btnModuleAdminActionPerformed

    private void btnAssignmentAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentAdminActionPerformed
        getFrameManager().showSub(ASSIGNMENT);
    }//GEN-LAST:event_btnAssignmentAdminActionPerformed

    private void btnGroupAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupAdminActionPerformed
        getFrameManager().showSub(GROUP);
    }//GEN-LAST:event_btnGroupAdminActionPerformed

    private void btnModuleTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuleTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModuleTeacherActionPerformed

    private void btnUserTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserTeacherActionPerformed

    private void btnTeacherTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeacherTeacherActionPerformed

    private void btnDepartmentTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartmentTeacherActionPerformed

    private void btnCourseTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseTeacherActionPerformed

    private void btnStudentTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentTeacherActionPerformed

    private void btnAssignmentsTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentsTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignmentsTeacherActionPerformed

    private void btnGroupTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGroupTeacherActionPerformed

    private void btnModuleStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuleStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModuleStudentActionPerformed

    private void btnUserStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserStudentActionPerformed

    private void btnTeacherStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeacherStudentActionPerformed

    private void btnDepartmentStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartmentStudentActionPerformed

    private void btnCourseStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCourseStudentActionPerformed

    private void btnStudentStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentStudentActionPerformed

    private void btnAssignmentsStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentsStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignmentsStudentActionPerformed

    private void btnGroupStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGroupStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignmentAdmin;
    private javax.swing.JButton btnAssignmentsStudent;
    private javax.swing.JButton btnAssignmentsTeacher;
    private javax.swing.JButton btnCourseAdmin;
    private javax.swing.JButton btnCourseStudent;
    private javax.swing.JButton btnCourseTeacher;
    private javax.swing.JButton btnDepartmentAdmin;
    private javax.swing.JButton btnDepartmentStudent;
    private javax.swing.JButton btnDepartmentTeacher;
    private javax.swing.JButton btnGroupAdmin;
    private javax.swing.JButton btnGroupStudent;
    private javax.swing.JButton btnGroupTeacher;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnModuleAdmin;
    private javax.swing.JButton btnModuleStudent;
    private javax.swing.JButton btnModuleTeacher;
    private javax.swing.JButton btnStudentAdmin;
    private javax.swing.JButton btnStudentStudent;
    private javax.swing.JButton btnStudentTeacher;
    private javax.swing.JButton btnTeacherAdmin;
    private javax.swing.JButton btnTeacherStudent;
    private javax.swing.JButton btnTeacherTeacher;
    private javax.swing.JButton btnUserAdmin;
    private javax.swing.JButton btnUserStudent;
    private javax.swing.JButton btnUserTeacher;
    private javax.swing.JPanel jAdminTabPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jStudentTabPanel;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jTeacherTabPanel;
    private javax.swing.JLabel lblLoggedInUsername;
    private javax.swing.JPanel pnlLoggedInAs4;
    // End of variables declaration//GEN-END:variables

}
