<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.4</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <modules>
        <module>model</module>
        <module>core</module>
        <module>backend</module>
        <module>desktop-app</module>
<!--        <module>android-app</module>-->
    </modules>

    <modelVersion>4.0.0</modelVersion>
    <groupId>ie.gti.asdl.rey.gtirecord</groupId>
    <artifactId>gti-record</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>21</maven.compiler.release>
        <exec.mainClass>ie.gti.asdl.rey.gtirecord.backend.GtiRecordRestServer</exec.mainClass>
        <spring.version>6.2.3</spring.version>
        <log4j.version>2.24.3</log4j.version>
        <java.version>21</java.version>
        <maven.version>3.9.4</maven.version>
    </properties>
    
    <dependencyManagement>
        <dependencies>

            <!-- Log4j 2 Core -->
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>${log4j.version}</version>
            </dependency>

            <!-- Log4j 2 API -->
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>${log4j.version}</version>
            </dependency>

            <!-- Bridge SLF4J to Log4j 2 (For Spring Compatibility) -->
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j-impl</artifactId>
                <version>${log4j.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>desktop</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <modules>
                <module>model</module>
                <module>core</module>
                <module>desktop-app</module>
            </modules>
        </profile>

        <profile>
            <id>backend</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <modules>
                <module>model</module>
                <module>core</module>
                <module>backend</module>
            </modules>
        </profile>

        <profile>
            <id>all</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <modules>
                <module>model</module>
                <module>core</module>
                <module>backend</module>
                <module>desktop-app</module>
            </modules>
        </profile>
    </profiles>

    <name>gti-record</name>
</project>