INSERT INTO `user` (id, person_id, username, password) VALUES (200, 200, 'brehenystacey200', 'gcs3J#He%2');
INSERT INTO `users_roles` (user_id, role_id) VALUES (200, 1);
INSERT INTO `user` (id, person_id, username, password) VALUES (127, 127, 'alan26127', 'w4&*EWgg^y');
INSERT INTO `users_roles` (user_id, role_id) VALUES (127, 1);
INSERT INTO `user` (id, person_id, username, password) VALUES (164, 164, 'keely31164', 'y3YGLn0E!j');
INSERT INTO `users_roles` (user_id, role_id) VALUES (164, 1);
INSERT INTO `user` (id, person_id, username, password) VALUES (168, 168, 'jacksonohagan168', 'Tco&44Uw3v');
INSERT INTO `users_roles` (user_id, role_id) VALUES (168, 1);
INSERT INTO `user` (id, person_id, username, password) VALUES (203, 203, 'qenright203', 'Rr3VEzXOh#');
INSERT INTO `users_roles` (user_id, role_id) VALUES (203, 1);
INSERT INTO `user` (id, person_id, username, password) VALUES (176, 176, 'mmcguinn176', 'p8Icr7Z(*L');
INSERT INTO `users_roles` (user_id, role_id) VALUES (176, 1);
INSERT INTO `user` (id, person_id, username, password) VALUES (196, 196, 'megan89196', '$yuLWO(Ey2');
INSERT INTO `users_roles` (user_id, role_id) VALUES (196, 1);
INSERT INTO `user` (id, person_id, username, password) VALUES (192, 192, 'qualtercolin192', 'N27qJERv(B');
INSERT INTO `users_roles` (user_id, role_id) VALUES (192, 1);
INSERT INTO `users_roles` (user_id, role_id) VALUES (192, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (135, 135, 'markcommins135', '54Sr4tp^^0');
INSERT INTO `users_roles` (user_id, role_id) VALUES (135, 1);
INSERT INTO `users_roles` (user_id, role_id) VALUES (135, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (140, 140, 'yhurd140', '*6JGfbyd*D');
INSERT INTO `users_roles` (user_id, role_id) VALUES (140, 1);
INSERT INTO `users_roles` (user_id, role_id) VALUES (140, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (173, 173, 'clairegilbane173', '%pS7znHco0');
INSERT INTO `users_roles` (user_id, role_id) VALUES (173, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (129, 129, 'broganallen129', '4JwzTZ+9&z');
INSERT INTO `users_roles` (user_id, role_id) VALUES (129, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (157, 157, 'hroche157', 'o^^pQcUU#0');
INSERT INTO `users_roles` (user_id, role_id) VALUES (157, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (151, 151, 'oliviamacevoy151', 'b$4hMezz^3');
INSERT INTO `users_roles` (user_id, role_id) VALUES (151, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (216, 216, 'ashtonlavan216', 'A7RRwTu*#7');
INSERT INTO `users_roles` (user_id, role_id) VALUES (216, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (131, 131, 'leah35131', '4t$Yn$Qp$+');
INSERT INTO `users_roles` (user_id, role_id) VALUES (131, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (169, 169, 'corleyrhianne169', 'V8)AsBls#6');
INSERT INTO `users_roles` (user_id, role_id) VALUES (169, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (141, 141, 'nathanielflaherty141', 'gCu#6A7f*q');
INSERT INTO `users_roles` (user_id, role_id) VALUES (141, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (177, 177, 'marcobranaola177', '_^MDkcoC#3');
INSERT INTO `users_roles` (user_id, role_id) VALUES (177, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (199, 199, 'mulroyamanda199', 'y+s5$Ntlcv');
INSERT INTO `users_roles` (user_id, role_id) VALUES (199, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (190, 190, 'lynsey51190', '4CdTQbjh+U');
INSERT INTO `users_roles` (user_id, role_id) VALUES (190, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (180, 180, 'lloyd69180', ')35Oo0&QYC');
INSERT INTO `users_roles` (user_id, role_id) VALUES (180, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (152, 152, 'hylandelisha152', 'rU1OH_ns)r');
INSERT INTO `users_roles` (user_id, role_id) VALUES (152, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (172, 172, 'jclaffey172', 'lb1WOrXe$n');
INSERT INTO `users_roles` (user_id, role_id) VALUES (172, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (184, 184, 'meaghankirke184', '8798BUh5(e');
INSERT INTO `users_roles` (user_id, role_id) VALUES (184, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (142, 142, 'dmilligan142', 'VdpMG!yh$6');
INSERT INTO `users_roles` (user_id, role_id) VALUES (142, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (161, 161, 'rhaugh161', '&7A0M)m@HT');
INSERT INTO `users_roles` (user_id, role_id) VALUES (161, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (213, 213, 'dgeraghty213', '%6rKwgnMh$');
INSERT INTO `users_roles` (user_id, role_id) VALUES (213, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (143, 143, 'ivorykirk143', ')!94Ei0Whh');
INSERT INTO `users_roles` (user_id, role_id) VALUES (143, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (174, 174, 'macdonaldkaty174', '_Vn5dMwl6T');
INSERT INTO `users_roles` (user_id, role_id) VALUES (174, 2);
INSERT INTO `user` (id, person_id, username, password) VALUES (128, 128, 'colin85128', 'KErM61PdX!');
INSERT INTO `users_roles` (user_id, role_id) VALUES (128, 2);
INSERT INTO `users_roles` (user_id, role_id) VALUES (128, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (134, 134, 'omar14134', '3bCYoOE7*W');
INSERT INTO `users_roles` (user_id, role_id) VALUES (134, 2);
INSERT INTO `users_roles` (user_id, role_id) VALUES (134, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (130, 130, 'howardshania130', '5NeL@7Ry&F');
INSERT INTO `users_roles` (user_id, role_id) VALUES (130, 2);
INSERT INTO `users_roles` (user_id, role_id) VALUES (130, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (220, 220, 'tomas43220', 'gw@3KdViWy');
INSERT INTO `users_roles` (user_id, role_id) VALUES (220, 2);
INSERT INTO `users_roles` (user_id, role_id) VALUES (220, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (191, 191, 'angus82191', '9%Zh0!BrDx');
INSERT INTO `users_roles` (user_id, role_id) VALUES (191, 2);
INSERT INTO `users_roles` (user_id, role_id) VALUES (191, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (167, 167, 'kcorcoran167', 'mw&60IEej_');
INSERT INTO `users_roles` (user_id, role_id) VALUES (167, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (207, 207, 'katherine90207', 'Y)&1Y+IgM#');
INSERT INTO `users_roles` (user_id, role_id) VALUES (207, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (188, 188, 'maeve93188', 'Ztn^1ARh&)');
INSERT INTO `users_roles` (user_id, role_id) VALUES (188, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (137, 137, 'mcousins137', 'W@6bXV@k!U');
INSERT INTO `users_roles` (user_id, role_id) VALUES (137, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (183, 183, 'kerrimulvihill183', 'D_bp7C9pmS');
INSERT INTO `users_roles` (user_id, role_id) VALUES (183, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (208, 208, 'emmet68208', '!8YOK$7n9O');
INSERT INTO `users_roles` (user_id, role_id) VALUES (208, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (160, 160, 'sarah-louisefinegan160', 'I4o8wZAr%e');
INSERT INTO `users_roles` (user_id, role_id) VALUES (160, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (209, 209, 'brooklynglazier209', 'p88IvXme)V');
INSERT INTO `users_roles` (user_id, role_id) VALUES (209, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (154, 154, 'jordan86154', '*GGIBNtw5k');
INSERT INTO `users_roles` (user_id, role_id) VALUES (154, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (178, 178, 'declan71178', '_qx^j7Ax(C');
INSERT INTO `users_roles` (user_id, role_id) VALUES (178, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (125, 125, 'connellnaoise125', '&y_4*Hx#C%');
INSERT INTO `users_roles` (user_id, role_id) VALUES (125, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (193, 193, 'kgaynard193', 'X1T_M66m#s');
INSERT INTO `users_roles` (user_id, role_id) VALUES (193, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (170, 170, 'kerry46170', '+GN5OUzjy4');
INSERT INTO `users_roles` (user_id, role_id) VALUES (170, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (219, 219, 'zoe39219', 'Xg3aoUsZA^');
INSERT INTO `users_roles` (user_id, role_id) VALUES (219, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (185, 185, 'aideen62185', 'q$2Z0tvr9q');
INSERT INTO `users_roles` (user_id, role_id) VALUES (185, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (201, 201, 'xwhelehan201', 'RLbAViv(@6');
INSERT INTO `users_roles` (user_id, role_id) VALUES (201, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (139, 139, 'ohearuth139', '$#D(5ReF%6');
INSERT INTO `users_roles` (user_id, role_id) VALUES (139, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (217, 217, 'fdalton217', 'd)K6IyFbZ%');
INSERT INTO `users_roles` (user_id, role_id) VALUES (217, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (186, 186, 'hanrattymelanie186', '_6ATbi33q9');
INSERT INTO `users_roles` (user_id, role_id) VALUES (186, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (144, 144, 'fergustiernan144', 'q2EkVD7v%(');
INSERT INTO `users_roles` (user_id, role_id) VALUES (144, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (132, 132, 'obryengabrielle132', 'j$QLx9NxcB');
INSERT INTO `users_roles` (user_id, role_id) VALUES (132, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (198, 198, 'clarkdoogan198', 'SCz9LWUs%a');
INSERT INTO `users_roles` (user_id, role_id) VALUES (198, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (146, 146, 'chelseamartin146', '6JNF+x%n**');
INSERT INTO `users_roles` (user_id, role_id) VALUES (146, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (159, 159, 'oonagh16159', 'xWE6Xab(o^');
INSERT INTO `users_roles` (user_id, role_id) VALUES (159, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (211, 211, 'kieransblaine211', 'AD!#T4Wy#h');
INSERT INTO `users_roles` (user_id, role_id) VALUES (211, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (150, 150, 'ashtonmacdonagh150', 'W5+Y$sKJ+I');
INSERT INTO `users_roles` (user_id, role_id) VALUES (150, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (149, 149, 'sdenison149', '_$9W!APq6C');
INSERT INTO `users_roles` (user_id, role_id) VALUES (149, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (156, 156, 'bronachstephenson156', '+3^pQ@rpUU');
INSERT INTO `users_roles` (user_id, role_id) VALUES (156, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (206, 206, 'jason97206', 'o5VCHnDC+P');
INSERT INTO `users_roles` (user_id, role_id) VALUES (206, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (158, 158, 'shauna23158', '0+2^wIMgU@');
INSERT INTO `users_roles` (user_id, role_id) VALUES (158, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (138, 138, 'olooneydairine138', 'VE^M#FZi_4');
INSERT INTO `users_roles` (user_id, role_id) VALUES (138, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (194, 194, 'obeirnkathy194', 'N+K*sDet_3');
INSERT INTO `users_roles` (user_id, role_id) VALUES (194, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (212, 212, 'beth46212', '$&5CTV6pxt');
INSERT INTO `users_roles` (user_id, role_id) VALUES (212, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (163, 163, 'amy-leemacconnaghy163', 'e6TZCEtw_t');
INSERT INTO `users_roles` (user_id, role_id) VALUES (163, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (179, 179, 'mcdonaldtrevor179', 'N43^oKynr#');
INSERT INTO `users_roles` (user_id, role_id) VALUES (179, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (145, 145, 'jackgearty145', 'f$E9xZhf5+');
INSERT INTO `users_roles` (user_id, role_id) VALUES (145, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (148, 148, 'xogrady148', 'I6QWq$NF%e');
INSERT INTO `users_roles` (user_id, role_id) VALUES (148, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (214, 214, 'dearbhail82214', '&u1HHo&4B*');
INSERT INTO `users_roles` (user_id, role_id) VALUES (214, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (202, 202, 'wdurnin202', '+^6OSft(97');
INSERT INTO `users_roles` (user_id, role_id) VALUES (202, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (215, 215, 'hcomber215', 'a9f9!RU1*Q');
INSERT INTO `users_roles` (user_id, role_id) VALUES (215, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (195, 195, 'comalley195', 'h_65aLVi)E');
INSERT INTO `users_roles` (user_id, role_id) VALUES (195, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (147, 147, 'scallaghan147', '$0AHZg#Z9p');
INSERT INTO `users_roles` (user_id, role_id) VALUES (147, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (218, 218, 'corrie67218', 'd&k75FJp19');
INSERT INTO `users_roles` (user_id, role_id) VALUES (218, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (162, 162, 'sforbes162', '*tOKZk%bI5');
INSERT INTO `users_roles` (user_id, role_id) VALUES (162, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (171, 171, 'doohanclifford171', '$5+LmK^_FB');
INSERT INTO `users_roles` (user_id, role_id) VALUES (171, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (175, 175, 'fionnualasharry175', 'j83XdD2i&0');
INSERT INTO `users_roles` (user_id, role_id) VALUES (175, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (204, 204, 'tiarnan22204', 'y^5O8UHd)r');
INSERT INTO `users_roles` (user_id, role_id) VALUES (204, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (123, 123, 'kmeehan123', '@2K)nSViuP');
INSERT INTO `users_roles` (user_id, role_id) VALUES (123, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (124, 124, 'jacob25124', '+oLYSqARP3');
INSERT INTO `users_roles` (user_id, role_id) VALUES (124, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (181, 181, 'cowencalum181', '3_X#9SIu6l');
INSERT INTO `users_roles` (user_id, role_id) VALUES (181, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (210, 210, 'financourtney210', 'D&p7ODHgQ*');
INSERT INTO `users_roles` (user_id, role_id) VALUES (210, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (197, 197, 'jjameson197', '@0xsJvfm+z');
INSERT INTO `users_roles` (user_id, role_id) VALUES (197, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (153, 153, 'dronan153', '$8WobSl*)3');
INSERT INTO `users_roles` (user_id, role_id) VALUES (153, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (155, 155, 'aoifewalls155', 'LS1MXq*Fz%');
INSERT INTO `users_roles` (user_id, role_id) VALUES (155, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (166, 166, 'cring166', 'CNLWEwX0!0');
INSERT INTO `users_roles` (user_id, role_id) VALUES (166, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (221, 221, 'eloughry221', '!IAKqYWva5');
INSERT INTO `users_roles` (user_id, role_id) VALUES (221, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (136, 136, 'ionamcgroarty136', '#(Bs+dIj3q');
INSERT INTO `users_roles` (user_id, role_id) VALUES (136, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (205, 205, 'nicola78205', 'tDE5FZdo&6');
INSERT INTO `users_roles` (user_id, role_id) VALUES (205, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (182, 182, 'eloise58182', 'USs4Jj_d+^');
INSERT INTO `users_roles` (user_id, role_id) VALUES (182, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (122, 122, 'kara42122', '5$945*Xs@_');
INSERT INTO `users_roles` (user_id, role_id) VALUES (122, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (165, 165, 'wgreene165', '%i55goJuIn');
INSERT INTO `users_roles` (user_id, role_id) VALUES (165, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (126, 126, 'bryan04126', ')z9ODoMk(0');
INSERT INTO `users_roles` (user_id, role_id) VALUES (126, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (133, 133, 'stewart93133', '#Q&bUmB679');
INSERT INTO `users_roles` (user_id, role_id) VALUES (133, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (187, 187, 'naoimh53187', '+c1riOZjF!');
INSERT INTO `users_roles` (user_id, role_id) VALUES (187, 3);
INSERT INTO `user` (id, person_id, username, password) VALUES (189, 189, 'etuohy189', 'cWYhREt((3');
INSERT INTO `users_roles` (user_id, role_id) VALUES (189, 3);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (192, 'Assistant Professor', 'MA', 5);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (135, 'Senior Lecturer', 'MA', 9);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (140, 'Assistant Professor', 'MSc', 11);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (173, 'Senior Lecturer', 'MSc', 19);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (129, 'Lecturer', 'MA', 25);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (157, 'Lecturer', 'MA', 9);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (151, 'Senior Lecturer', 'MSc', 5);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (216, 'Lecturer', 'MA', 20);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (131, 'Assistant Professor', 'MSc', 23);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (169, 'Assistant Professor', 'MA', 9);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (141, 'Assistant Professor', 'MA', 25);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (177, 'Senior Lecturer', 'PhD', 12);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (199, 'Assistant Professor', 'PhD', 21);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (190, 'Senior Lecturer', 'PhD', 13);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (180, 'Assistant Professor', 'MA', 12);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (152, 'Senior Lecturer', 'PhD', 20);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (172, 'Assistant Professor', 'MSc', 22);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (184, 'Senior Lecturer', 'MA', 14);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (142, 'Lecturer', 'MSc', 25);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (161, 'Assistant Professor', 'MA', 25);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (213, 'Senior Lecturer', 'PhD', 12);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (143, 'Lecturer', 'PhD', 18);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (174, 'Assistant Professor', 'MA', 10);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (128, 'Lecturer', 'MA', 6);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (134, 'Lecturer', 'PhD', 14);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (130, 'Senior Lecturer', 'MSc', 21);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (220, 'Senior Lecturer', 'MSc', 19);
INSERT INTO `teacher` (person_id, position, degree, work_experience) VALUES (191, 'Assistant Professor', 'PhD', 8);
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (167, 1, 'English Literature', 0, 'Jackson Sheilds: 0862999533');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (207, 1, 'English Literature', 0, 'Brogan Gwynn: 0898972670');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (188, 1, 'Engineering', 0, 'Dr. Ashlene Salmon: 0866119268');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (137, 1, 'Nursing', 0, 'Sharon Cloone: 0896670178');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (183, 1, 'Mathematics', 1, 'Caitlyn Scriven: 0833958620');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (208, 1, 'Computer Science', 0, 'Jody Cogley: 0891559749');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (160, 1, 'Engineering', 1, 'Jordan MacCann: 0878354163');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (209, 1, 'Law', 1, 'Mrs. Helen Keaveny: 0896173470');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (154, 1, 'Business Administration', 0, 'Mrs. Robyn Hassett: 0852033251');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (178, 1, 'Computer Science', 0, 'Annie Carthy-Moran: 0876799847');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (125, 1, 'Art and Design', 0, 'Orfhlaith Comisky: 0876268157');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (193, 1, 'Law', 0, 'Amy-Leigh Connelly: 0837503161');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (170, 1, 'Law', 0, 'Alex Leacy: 0872584011');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (219, 1, 'Computer Science', 0, 'Charlie Dulohery: 0854551740');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (185, 1, 'Mathematics', 0, 'Dr. Joshua McGuirk: 0833645493');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (201, 1, 'Computer Science', 1, 'Theresa McGoldrick: 0895124859');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (139, 1, 'Business Administration', 0, 'Aoibhinn Thom: 0879031353');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (217, 1, 'Business Administration', 1, 'Jesse Dillane: 0896284286');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (186, 1, 'Mathematics', 0, 'Robin McLeese: 0857801448');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (144, 1, 'English Literature', 0, 'Cailin Heavey: 0896792881');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (132, 1, 'Computer Science', 0, 'Mrs. Rosie Bradden: 0865662724');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (198, 1, 'English Literature', 0, 'Mitchell Tooman-Moriarty: 0895273143');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (146, 1, 'Nursing', 0, 'Grainne Henry: 0896343187');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (159, 1, 'English Literature', 1, 'Micheal McCabe: 0858733719');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (211, 1, 'Art and Design', 0, 'Gareth Ginevan: 0893672879');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (150, 1, 'Mathematics', 0, 'Mrs. Alex Moher: 0833717016');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (149, 1, 'Mathematics', 0, 'Sandra Biesty-Hourican: 0893405036');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (156, 1, 'Law', 0, 'Breandan Darmody: 0831221114');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (206, 1, 'Computer Science', 1, 'Alexandra Nicholson-Caulfield: 0891384431');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (158, 1, 'Engineering', 0, 'Bailey McQuade: 0830701268');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (138, 1, 'Law', 1, 'Cortney Thompson: 0869531111');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (194, 1, 'Computer Science', 0, 'Bernard Dyer: 0834183345');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (212, 1, 'Nursing', 0, 'Eileen Hillery: 0865555183');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (163, 1, 'Business Administration', 0, 'Miss Lesley MacKevitt: 0874251387');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (179, 1, 'Mathematics', 0, 'Graham Ervin: 0869103882');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (145, 1, 'English Literature', 0, 'Mr. Leo Lowney: 0896927767');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (148, 1, 'Computer Science', 1, 'Brad Whalen-Garavan: 0833537213');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (214, 1, 'Engineering', 0, 'Dr. Russell Reid: 0876699901');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (202, 1, 'Art and Design', 0, 'Jay McGuigan: 0877796050');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (215, 1, 'Computer Science', 0, 'Dr. Lewis Meagher: 0835338407');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (195, 1, 'Engineering', 0, 'Graeme McGlinchey: 0860122686');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (147, 1, 'English Literature', 0, 'Robin O''Riordan: 0872431028');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (218, 1, 'Engineering', 0, 'Eamonn Lowry: 0838015874');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (162, 1, 'Mathematics', 0, 'Ms. Shannen O''Hanlon: 0835278767');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (171, 1, 'Nursing', 0, 'Samuel Melvin: 0894418838');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (175, 1, 'Engineering', 1, 'Laoise Spain: 0890609717');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (204, 1, 'Engineering', 0, 'Keith Hunter: 0860334482');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (123, 1, 'Business Administration', 0, 'Dermot Magee-Coughlan: 0896104410');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (124, 1, 'Art and Design', 0, 'Susanna McGarvey: 0854540211');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (181, 1, 'Mathematics', 0, 'Robert Glazier: 0839931095');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (210, 1, 'Business Administration', 0, 'Fionntan McGlynn: 0833963541');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (197, 1, 'Computer Science', 0, 'Mr. Brian Gilroy: 0863248021');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (153, 1, 'English Literature', 0, 'Mr. Nicholas Hamilton: 0854641931');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (155, 1, 'Art and Design', 0, 'Miss Eleanor Bernie: 0872709110');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (166, 1, 'Law', 0, 'Daryl Diffin: 0871255213');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (221, 1, 'Engineering', 0, 'Dr. Dana Guinness: 0839297502');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (136, 1, 'Mathematics', 1, 'Daire Victory: 0892880346');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (205, 1, 'Engineering', 1, 'Sarah-Louise Lang: 0853764652');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (182, 1, 'Business Administration', 1, 'Joy Stokes: 0868060618');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (122, 1, 'Business Administration', 0, 'Dr. Hamish Keoghan: 0876618891');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (165, 1, 'Computer Science', 0, 'Keely Reynoldson: 0867971518');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (126, 1, 'Art and Design', 0, 'Ayesha O''Mahoney: 0830674227');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (133, 1, 'Business Administration', 0, 'Dr. Dermot McGarry: 0856402325');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (187, 1, 'English Literature', 0, 'Jamie-Lee Carty: 0875259337');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (189, 1, 'Engineering', 0, 'Terri Healy-Fair: 0866170966');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (128, 1, 'Mathematics', 0, 'Fergus Walls: 0839901582');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (134, 1, 'Art and Design', 0, 'Lindsay Miscell-Linskey: 0890273454');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (130, 1, 'Business Administration', 0, 'Dean Magauran: 0893752653');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (220, 1, 'Computer Science', 0, 'Kane Igoe: 0897158805');
INSERT INTO `student` (person_id, group_id, education, is_on_erasmus, emergency_contacts) VALUES (191, 1, 'Mathematics', 1, 'Kori Marley: 0873233555');