package ie.gti.asdl.rey.gtirecord.core;

import ie.gti.asdl.rey.gtirecord.core.service.*;
import lombok.Getter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


/**
 * Central manager that aggregates all service beans used across the application.
 * <p>
 * This class acts as a single access point for the various domain services
 * (e.g. {@link UserService}, {@link CourseService}, {@link StudentService}, etc.),
 * allowing consumers to depend on a single {@code ServiceManager} instance rather
 * than injecting each service individually. All dependencies are injected via
 * constructor injection and exposed as read-only getters (generated by Lombok's
 * {@link Getter @Getter} annotation).
 */
@Getter
@Component
public class ServiceManager {

    /** Service handling user-related operations. */
    private final UserService userService;

    /** Service handling address-related operations. */
    private final AddressService addressService;

    /** Service handling person-related operations. */
    private final PersonService personService;

    /** Service handling department-related operations. */
    private final DepartmentService departmentService;

    /** Service handling module-related operations. */
    private final ModuleService moduleService;

    /** Service handling course-related operations. */
    private final CourseService courseService;

    /** Service handling course-module association operations. */
    private final CourseModuleService courseModuleService;

    /** Service handling teacher-related operations. */
    private final TeacherService teacherService;

    /** Service handling student-related operations. */
    private final StudentService studentService;

    /** Service handling teacher-module association operations. */
    private final TeacherModuleService teacherModuleService;

    /** Service handling group-related operations. */
    private final GroupService groupService;

    /** Service handling group-module association operations. */
    private final GroupModuleService groupModuleService;

    /** Service handling assignment-related operations. */
    private final AssignmentService assignmentService;

    /** Service handling student-assignment association operations. */
    private final StudentAssignmentService studentAssignmentService;

    /**
     * Constructs a new {@code ServiceManager} with all required service dependencies
     * injected by Spring.
     *
     * @param userService              the user service
     * @param addressService           the address service
     * @param personService            the person service
     * @param departmentService        the department service
     * @param moduleService            the module service
     * @param courseService            the course service
     * @param courseModuleService      the course-module association service
     * @param teacherService           the teacher service
     * @param studentService           the student service
     * @param teacherModuleService     the teacher-module association service
     * @param groupService             the group service
     * @param groupModuleService       the group-module association service
     * @param assignmentService        the assignment service
     * @param studentAssignmentService the student-assignment association service
     */
    @Autowired
    public ServiceManager(UserService userService, AddressService addressService, PersonService personService, DepartmentService departmentService,
                          ModuleService moduleService, CourseService courseService, CourseModuleService courseModuleService,
                          TeacherService teacherService, StudentService studentService, TeacherModuleService teacherModuleService,
                          GroupService groupService, GroupModuleService groupModuleService, AssignmentService assignmentService,
                          StudentAssignmentService studentAssignmentService) {
        this.userService = userService;
        this.addressService = addressService;
        this.personService = personService;
        this.departmentService = departmentService;
        this.moduleService = moduleService;
        this.courseService = courseService;
        this.courseModuleService = courseModuleService;
        this.teacherService = teacherService;
        this.studentService = studentService;
        this.teacherModuleService = teacherModuleService;
        this.groupService = groupService;
        this.groupModuleService = groupModuleService;
        this.assignmentService = assignmentService;
        this.studentAssignmentService = studentAssignmentService;
    }

}
